<a href="https://colab.research.google.com/github/divyatejaswi86/Datascience-projects/blob/main/NBA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_csv('nba.csv')
df

,Name,Team,Number,Position,Age,Height(Inch),Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,6.2,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,6.6,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,6.5,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,6.5,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,6.1,231,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,6.1,234,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,6.3,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,6.1,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,7.3,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7.0,231,Kansas,947276.0

In [2]:
# Rows and Columns
df.shape

(457, 9)

In [3]:
# Size of the datset
df.size

4113

In [4]:
# Description of the datset
df.describe()

           Number         Age  Height(Inch)      Weight        Salary
count  457.000000  457.000000    457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731      6.517133  221.522976  4.842684e+06
std     15.966090    4.404016      0.352205   26.368343  5.229238e+06
min      0.000000   19.000000      5.110000  161.000000  3.088800e+04
25%      5.000000   24.000000      6.110000  200.000000  1.044792e+06
50%     13.000000   26.000000      6.600000  220.000000  2.839073e+06
75%     25.000000   30.000000      6.800000  240.000000  6.500000e+06
max     99.000000   40.000000      7.300000  307.000000  2.500000e+07

In [5]:
# Information of the datset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          457 non-null    object
 1   Team          457 non-null    object
 2   Number        457 non-null    int64
 3   Position      457 non-null    object
 4   Age           457 non-null    int64
 5   Height(Inch)  457 non-null    float64
 6   Weight        457 non-null    int64
 7   College       373 non-null    object
 8   Salary        446 non-null    float64
dtypes: float64(2), int64(3), object(4)
memory usage: 32.3+ KB

In [6]:
# Checking null values
df.isnull().sum()

Name             0
Team             0
Number           0
Position         0
Age              0
Height(Inch)     0
Weight           0
College         84
Salary          11
dtype: int64

In [7]:
# Drop rows (25,72,63) from the NBA dataset. What is the average age of the players after dropping the rows?
# Note: Please do not change the original dataset.
df1 = df.drop([25,72,63])
df1

,Name,Team,Number,Position,Age,Height(Inch),Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,6.2,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,6.6,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,6.5,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,6.5,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,6.1,231,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,6.1,234,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,6.3,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,6.1,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,7.3,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7.0,231,Kansas,947276.0

In [8]:
df1['Age'].mean()

np.float64(26.916299559471366)

In [9]:
# Rename column 'Number' to 'Chest_Number' and 'Weight' to 'Weight(lbs)' in the NBA dataset
df.rename(columns = {'Number':'Chest_Number','Weight':'Weight(lbs)'}, inplace = True)

In [10]:
df.rename(columns = {'Height(Inch)':'Height(ft)'}, inplace = True)

In [11]:
# @title Q1
# Find the name of the player with highest salary
highest_sal = df['Salary'].max()
df[df['Salary'] == highest_sal][['Name','Salary']]

# df[rows][columns]

            Name      Salary
109  Kobe Bryant  25000000.0

In [12]:
# @title Q2
# Find the no.of players weighing above 180 pounds
df[df['Weight(lbs)'] > 180]['Weight(lbs)'].count()

np.int64(431)

In [13]:
# @title Q3
# Filter out all the players with height less than 6.2 and count the no.of players
a = df[df['Height(ft)'] < 6.2]
print(a)
a['Height(ft)'].count()

                 Name                    Team  Chest_Number Position  Age  \
4       Jonas Jerebko          Boston Celtics             8       PF   29
11      Isaiah Thomas          Boston Celtics             4       PG   27
22       Shane Larkin           Brooklyn Nets             0       PG   23
24   Chris McCullough           Brooklyn Nets             1       PF   21
25        Willie Reed           Brooklyn Nets            33       PF   26
..                ...                     ...           ...      ...  ...
440     Brian Roberts  Portland Trail Blazers             2       PG   30
443        Trey Burke               Utah Jazz             3       PG   23
446    Derrick Favors               Utah Jazz            15       PF   24
452        Trey Lyles               Utah Jazz            41       PF   20
454         Raul Neto               Utah Jazz            25       PG   24

     Height(ft)  Weight(lbs)       College      Salary
4          6.10          231           NaN   5000000.0
11         5.90          185    Washington   6912869.0
22         5.11          175    Miami (FL)   1500000.0
24         6.11          200      Syracuse   1140240.0
25         6.10          220   Saint Louis    947276.0
..          ...          ...           ...         ...
440        6.10          173        Dayton   2854940.0
443        6.10          191      Michigan   2658240.0
446        6.10          265  Georgia Tech  12000000.0
452        6.10          234      Kentucky   2239800.0
454        6.10          179           NaN    900000.0

[117 rows x 9 columns]

np.int64(117)

In [14]:
# @title Q4
# Filter the data with more than 35 years of age.
# Find the no.of records for the "PF" position
df[(df['Age'] > 35) & (df['Position'] == 'PF')]['Age'].count()

np.int64(6)

In [15]:
# @title Q5
# Which team value has the highest occurance in the data
df['Team'].value_counts().reset_index()

                      Team  count
0     New Orleans Pelicans     19
1        Memphis Grizzlies     18
2          New York Knicks     16
3          Milwaukee Bucks     16
4            Brooklyn Nets     15
5           Boston Celtics     15
6     Los Angeles Clippers     15
7       Los Angeles Lakers     15
8             Phoenix Suns     15
9         Sacramento Kings     15
10           Chicago Bulls     15
11      Philadelphia 76ers     15
12         Toronto Raptors     15
13   Golden State Warriors     15
14          Indiana Pacers     15
15         Detroit Pistons     15
16     Cleveland Cavaliers     15
17        Dallas Mavericks     15
18         Houston Rockets     15
19       San Antonio Spurs     15
20           Atlanta Hawks     15
21       Charlotte Hornets     15
22              Miami Heat     15
23      Washington Wizards     15
24          Denver Nuggets     15
25   Oklahoma City Thunder     15
26               Utah Jazz     15
27  Portland Trail Blazers     15
28           Orlando Magic     14
29  Minnesota Timberwolves     14

In [16]:
# @title Q6
# Which team has the highest no.of youngest players (Age less than or equal to 25) playing in the position "PF" or "SF".
df[(df['Age'] <= 25) & (df['Position'].isin(['PF','SF']))]['Team'].value_counts().reset_index()

                      Team  count
0            Chicago Bulls      6
1       Philadelphia 76ers      5
2   Portland Trail Blazers      5
3          Houston Rockets      5
4          Milwaukee Bucks      5
5           Indiana Pacers      4
6          New York Knicks      4
7       Los Angeles Lakers      4
8          Detroit Pistons      4
9        Memphis Grizzlies      4
10   Golden State Warriors      3
11        Sacramento Kings      3
12  Minnesota Timberwolves      3
13   Oklahoma City Thunder      2
14               Utah Jazz      2
15           Brooklyn Nets      2
16         Toronto Raptors      2
17          Boston Celtics      2
18           Orlando Magic      2
19       San Antonio Spurs      2
20    New Orleans Pelicans      2
21      Washington Wizards      2
22            Phoenix Suns      1
23    Los Angeles Clippers      1
24        Dallas Mavericks      1
25       Charlotte Hornets      1
26           Atlanta Hawks      1
27          Denver Nuggets      1
28              Miami Heat      1

In [17]:
# @title Q7
# What is the sum of the salaries of all the players with chest number 41?
print(df[df['Chest_Number'] == 41]['Salary'].sum())

22264701.0

In [18]:
# @title Q8
# What is the average salary recieved by players who are 23 or younger in the team 'Chicago Bulls'
print(df[(df['Age'] <= 23) & (df['Team'] == 'Chicago Bulls')]['Salary'].mean())

958126.5

In [19]:
# @title Q9
# What is the average age of players from rows 201 to 250?
cond = df.loc[201:250] # In location function it doesn't have n-1 attribute
cond['Age'].mean()

np.float64(26.62)

In [20]:
# Creating a New Column
df['Weight(Kgs)'] = df['Weight(lbs)'] * 0.45359237

In [21]:
# @title Q10
# What is the weight in KGs for 112th record (111th Index)?
df.loc[111, 'Weight(Kgs)']

np.float64(122.4699399)

In [22]:
df['Height(Mts)'] = df['Height(ft)'] / 3.28084

In [23]:
# Calculate BMI of the players
df['BMI'] = df['Weight(Kgs)'] / (df['Height(Mts)'] ** 2)

In [24]:
'''
Create a new columns with the name "BMI Evaluation".
Assign the BMI status based on the following condition,
BMI <= 18.4 - "Underweight"
BMI <= 24.9 - "Healthy"
BMI <= 29.9 - "Over Weight"
BMI <= 34.9 - "Severly Over Weight"
BMI <= 39.9 - "Obese"
BMI > 39.9 - "Severly Obese"
'''
# Create a empty list to store categories
BMI_Category = []

# Loop through BMI values
for bmi in df['BMI']:
  if bmi <= 18.4:
    BMI_Category.append("Underweight")
  elif bmi <= 24.9:
    BMI_Category.append("Healthy")
  elif bmi <= 29.9:
    BMI_Category.append("Overweight")
  elif bmi <= 34.9:
    BMI_Category.append("Severly Overweight")
  elif bmi <= 39.9:
    BMI_Category.append("Obese")
  else:
    BMI_Category.append("Severly Obese")


df['BMI_Category'] = BMI_Category

In [25]:
# @title Q11
# Check the count of different categories in BMI Category
df['BMI_Category'].value_counts().reset_index()

         BMI_Category  count
0             Healthy    262
1          Overweight    115
2  Severly Overweight     68
3               Obese     11
4       Severly Obese      1

In [26]:
# @title Q12
# Find the total salary spent by each team on thier players
df.groupby(by = 'Team')['Salary'].sum().reset_index()

                      Team       Salary
0            Atlanta Hawks   72902950.0
1           Boston Celtics   58541068.0
2            Brooklyn Nets   52528475.0
3        Charlotte Hornets   78340920.0
4            Chicago Bulls   86783378.0
5      Cleveland Cavaliers  106988689.0
6         Dallas Mavericks   71198732.0
7           Denver Nuggets   60121930.0
8          Detroit Pistons   67168263.0
9    Golden State Warriors   88868997.0
10         Houston Rockets   75283021.0
11          Indiana Pacers   66751826.0
12    Los Angeles Clippers   94854640.0
13      Los Angeles Lakers   71770431.0
14       Memphis Grizzlies   76550880.0
15              Miami Heat   82515673.0
16         Milwaukee Bucks   69603517.0
17  Minnesota Timberwolves   59709697.0
18    New Orleans Pelicans   82750774.0
19         New York Knicks   73303898.0
20   Oklahoma City Thunder   93765298.0
21           Orlando Magic   60161470.0
22      Philadelphia 76ers   30992894.0
23            Phoenix Suns   63445135.0
24  Portland Trail Blazers   48301818.0
25        Sacramento Kings   71683666.0
26       San Antonio Spurs   84442733.0
27         Toronto Raptors   71117611.0
28               Utah Jazz   63060091.0
29      Washington Wizards   76328636.0

In [27]:
# @title Q13
# Find the Different BMI Category count based on the Team
df.groupby(by = ['Team','BMI_Category'])['BMI'].count()

Team                BMI_Category
Atlanta Hawks       Healthy                9
                    Overweight             3
                    Severly Overweight     3
Boston Celtics      Healthy                9
                    Overweight             5
                                          ..
Utah Jazz           Healthy               11
                    Overweight             2
                    Severly Overweight     2
Washington Wizards  Healthy               11
                    Severly Overweight     4
Name: BMI, Length: 100, dtype: int64